# Generated by Django 4.0.6 on 2023-03-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkAnomalyDetection', '0008_anomalytraffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalytraffic',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
