# Generated by Django 4.0.6 on 2023-03-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkAnomalyDetection', '0009_anomalytraffic_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalytraffic',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
