# Generated by Django 4.0.6 on 2023-03-11 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkAnomalyDetection', '0011_alter_anomalytraffic_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalytraffic',
            old_name='time_stamp',
            new_name='first_time_stamp',
        ),
        migrations.AddField(
            model_name='anomalytraffic',
            name='last_time_stamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
