# Generated by Django 4.0.6 on 2023-03-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkAnomalyDetection', '0012_rename_time_stamp_anomalytraffic_first_time_stamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyTraffic1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time_stamp', models.CharField(max_length=100)),
                ('last_time_stamp', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('src_ip', models.CharField(max_length=100)),
                ('dst_ip', models.CharField(max_length=100)),
                ('src_port', models.CharField(max_length=100)),
                ('dst_port', models.CharField(max_length=100)),
                ('anomaly_type', models.CharField(max_length=100)),
            ],
        ),
    ]
